# .github/workflows/roku-ci.yml

name: Roku CI/CD
on:
  push:
    branches:
      - test
      
jobs:
  build-deploy-test:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          git fetch origin test
          git checkout test
          git reset --hard origin/test

      - name: Run BrighterScript build
        run: bsc
        working-directory: ./
      
      - name: Start Roku debug log capture in background
        run: |
          nohup nc 10.71.71.152 8085 > roku_telnet_log.txt 2>&1 &
          echo $! > telnet_pid.txt
        shell: bash
      
      - name: Run ECP tests
        run: node scripts/run-tests.js

      - name: Stop Roku debug log capture
        run: |
          kill $(cat telnet_pid.txt) || echo "Log capture process already stopped"
        shell: bash

      - name: Upload test output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test_output.json

      - name: Upload telnet logs
        uses: actions/upload-artifact@v4
        with:
          name: roku-telnet-logs
          path: roku_telnet_log.txt
